import Head from "next/head";
import styles from "@/styles/Home.module.css";
import React, {useState} from 'react';

export default function PaginaInicial() {
  const [numeroAleatorio, setNumeroAleatorio] = useState(0);

  function gerarNumero(){
    const novoNumero = Math.floor(Math.random() * (100-1) + 1);
    setNumeroAleatorio(novoNumero);
  }
  return (
    <div>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className = {styles.conteudo_centralizado}>
          <h3 className = {styles.numero_texto}>Número aleatório:</h3>
          <h1 className = {styles.numero_aleatorio}>{numeroAleatorio}</h1>

          <div className ={styles.area_botao}>
              <label>
                Click no botão abaixo para gerar um número aleatório:
              </label>
          </div>

          <button onClick = {gerarNumero} className = {styles.botao}>
              Gerar número
          </button>
      </div>
      
    </div>
  );
}
